import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = (path) => readFileSync(resolve(root, path), 'utf8').replaceAll('\r\n', '\n');
const template = read('templates/app.html');
const version = createHash('sha256').update(read('app.js') + read('styles.css') + template + read('locales/it.json') + read('locales/de.json')).digest('hex').slice(0, 12);
const escape = (text) => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

for (const lang of ['it', 'de']) {
  const config = JSON.parse(read(`locales/${lang}.json`));
  const values = { ...config.messages, lang, version };
  const html = template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!(key in values)) throw new Error(`Missing translation: ${lang}.${key}`);
    return escape(values[key]);
  });
  mkdirSync(resolve(root, lang), { recursive: true });
  writeFileSync(resolve(root, lang, 'index.html'), html);
  writeFileSync(resolve(root, lang, 'config.js'), `// Generated by scripts/build.mjs. Edit locales/${lang}.json.\nwindow.PRAYER_APP = Object.freeze(${JSON.stringify(config, null, 2)});\n`);
  const manifest = JSON.parse(read('site.webmanifest'));
  Object.assign(manifest, { name: config.messages.appName, short_name: config.messages.title, description: config.messages.description, lang, id: './', start_url: './', scope: './' });
  manifest.icons = manifest.icons.map(icon => ({ ...icon, src: '../' + icon.src }));
  writeFileSync(resolve(root, lang, 'site.webmanifest'), JSON.stringify(manifest, null, 2) + '\n');
}
console.log('Built Italian and German pages.');
